version: "3.9"
services:
  collectd:
    image: hsmtkk/carbon-relay-ng_profile/collectd:latest
    deploy:
      replicas: 4
  bad-relay:
    image: hsmtkk/carbon-relay-ng_profile/carbon-relay-ng:latest
    volumes:
      - "./carbon-relay-ng/bad.ini:/usr/local/etc/carbon-relay-ng.ini:ro"
    ports:
      - "18081:8081"
  good-relay:
    image: hsmtkk/carbon-relay-ng_profile/carbon-relay-ng:latest
    volumes:
      - "./carbon-relay-ng/good.ini:/usr/local/etc/carbon-relay-ng.ini:ro"
    ports:
      - "28081:8081"
  graphite:
    image: graphiteapp/graphite-statsd:1.1.7-9
  process-exporter:
    image: ncabatoff/process-exporter:0.7.5
    privileged: true
    entrypoint:
      - process-exporter
      - -config.path
      - /usr/local/etc/process-exporter.yml
      - -procfs
      - /host/proc
    volumes:
      - "/proc:/host/proc"
      - "./process-exporter/process-exporter.yml:/usr/local/etc/process-exporter.yml:ro"
  prometheus:
    image: prom/prometheus
    volumes:
      - "./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro"
    ports:
      - "9090:9090"
